version: "3.9"

services:

  web-edu-container:
    image: web-hello
    ports:
      - "127.0.0.1:8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - D:/Projects/my_site/templates:/usr/src/app/templates
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - ./dev/var/postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "education_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"