# Generated by Django 4.1.1 on 2022-10-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название практической работы', max_length=80, unique=True)),
                ('description', models.TextField(help_text='Описание практической работы')),
            ],
        ),
    ]
