# Generated by Django 4.1.1 on 2022-10-06 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Количество баллов за работу', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(help_text='Комментарий к оценке')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(help_text='Оцениваемая практическая работа студента', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='education_app.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='students',
            field=models.ManyToManyField(related_name='student_works', through='education_app.Assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_works', through='education_app.Assessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
